language: python
services:
  - postgresql
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
script:
  - python manage.py migrate
  - python manage.py test
