# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 23:24
from __future__ import unicode_literals

import appTodolist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTodolist', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=appTodolist.models.new_priority),
        ),
    ]
